name: "yolo_ppe_v2"
platform: "tensorrt_plan"
max_batch_size: 8
input [
  {
    name: "images"
    data_type: TYPE_FP16
    dims: [3, 640, 640]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP16
    dims: [-1, 7]
  }
]
dynamic_batching {
  preferred_batch_size: [1, 4, 8]
  max_queue_delay_microseconds: 50
}
instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]
